---
- name : Configure bastion servers
  hosts: security
  become: yes
  become_user: root
  tasks :
    # - name: Install Aptitude
    #   apt:
    #     update_cache: yes
    #     name: aptitude

    # - name: Full update Ubuntu
    #   apt:
    #     update_cache: yes
    #     upgrade: full
    #   register: task_result

    # - name: (reboot) Reboot triggered
    #   command: /sbin/shutdown -r +1 "Ansible-triggered Reboot"
    #   async: 0
    #   poll: 0
    #   when: task_result is changed
 
    # - name: Wait for the reboot to complete if there was a change.
    #   wait_for_connection:
    #     connect_timeout: 30
    #     sleep: 60
    #     delay: 120
    #   when: task_result is changed
      
    - name: Install Squid
      apt:
        name: squid
        update_cache: yes

    - name: Allow connections to squid 
      lineinfile:
        dest: /etc/squid/squid.conf
        regexp: '^http_access deny all'
        line: 'http_access allow all'
    - name: always restart squid
      service: name=squid state=restarted

    - name: copy generated key with owner and permissions
      copy:
        src: /tmp/privkey.pem
        dest: /tmp/privkey.pem
        owner: root
        group: root
        mode: 0600

    - name: copy ansible config to bastion hosts
      copy:
        src: .ansible.cfg
        dest: /root/.ansible.cfg
        owner: root
        group: root
        mode: 0644
