---
- name : Install postgresql software on db nodes and init master
  hosts: db
  become: yes
  become_user: root
  vars:
    proxy_env:
      http_proxy: http://{{ hostvars[inventory_hostname].proxy }}:3128
      https_proxy: http://{{ hostvars[inventory_hostname].proxy }}:3128
      ftp_proxy: http://{{ hostvars[inventory_hostname].proxy }}:3128
  environment: "{{ proxy_env }} "
  tasks :
    # - name: Install Aptitude
    #   apt:
    #     name: aptitude

    # - name: Full update Ubuntu
    #   apt:
    #     upgrade: full
    #   register: task_result

    # - name: Install list of packages
    #   apt: name={{item}} state=installed
    #   with_items:
    #     - curl
    #     - openssh-server
    #     - ca-certificates
    #     - postfix

    # - name: (reboot) Reboot triggered
    #   command: /sbin/shutdown -r +1 "Ansible-triggered Reboot"
    #   async: 0
    #   poll: 0
    #   when: task_result is changed
 
    # - name: Wait for the reboot to complete if there was a change.
    #   wait_for_connection:
    #     connect_timeout: 30
    #     sleep: 60
    #     delay: 120
    #   when: task_result is changed
    - name: Modify /etc/environment
      lineinfile:
        path: /etc/environment
        line: LC_ALL="en_US.UTF-8"

    - name: Modify share mem parms
      lineinfile:
          path: /etc/sysctl.conf
          line: > 
            kernel.sem = 250 32000 32 262
            kernel.shmall = 4194304
            kernel.shmmax = 17179869184

    - name: Activate params
      shell:
        cmd: "cat /etc/sysctl.conf /etc/sysctl.d/*.conf  | sysctl -e -p -" 

    - name: Add gitlab pkg repo
      shell: 'curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | bash'
      
    - name: Creates directory
      file:
        path: /etc/gitlab
        state: directory
        owner: root
        group: root
        mode: 0600
    
    - name: Place GitLab omnibus configuration file with Postgres Role
      template:
        src: gitlab.rb.postgres.j2
        dest: /etc/gitlab/gitlab.rb
        owner: root
        group: root
        mode: 0600

    - name: Install gitlab omnibus 
      apt: name={{item}} state=present
      with_items:
        - gitlab-ee=12.0.0-ee.0 

    - name: Activate changes
      shell: "gitlab-ctl reconfigure"
      ignore_errors: True

    - name: Restart services
      shell: "gitlab-ctl restart"
